server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**

        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**

        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/api/storage/**

        - id: tts-service
          uri: lb://tts-service
          predicates:
            - Path=/api/tts/**

        - id: media-worker
          uri: lb://media-worker
          predicates:
            - Path=/api/worker/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
