server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/khushal4801/media-configs.git
          clone-on-start: true
          default-label: main
